version: "2.1"
services:
  wireguard:
    image: nginx:latest
    container_name: webmessage
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tomsk
    volumes:
      - /home/ParserBet2/:/usr/share/nginx/html/  
      - /home/webmessage/nginx.conf:/etc/nginx/nginx.conf  
      - /home/webmessage/conf-files/:/etc/nginx/conf.d/
      - /home/webmessage/log/:/var/log/nginx/ 
    ports:
      - 5142:80
    restart: unless-stopped
